# Travis CI is only used to check the lesson and is not involved in its deployment
dist: xenial  # Ubuntu 16.04 (required for python 3.7)
language: python
python: 3.7

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - R_LIBS_USER=~/R/Library
    - R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library

cache:
  apt: true
  bundler: true
  directories:
    - /home/travis/.rvm/
    - $R_LIBS_USER

branches:
  only:
  - gh-pages
  - /.*/

before_install:
  - sudo add-apt-repository -y "ppa:marutter/rrutter3.5"
  - sudo add-apt-repository -y "ppa:marutter/c2d4u3.5"
  - sudo add-apt-repository -y "ppa:ubuntugis/ppa"
  - sudo add-apt-repository -y "ppa:cran/travis"
  - travis_apt_get_update
  - sudo apt-get update -y
  - sudo apt-get install -y  --no-install-recommends r-base
  - sudo mkdir -p /usr/local/lib/R/site-library $R_LIBS_USER
  - sudo chmod 2777 /usr/local/lib/R /usr/local/lib/R/site-library $R_LIBS_USER
  - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > ~/.Rprofile.site
  - export R_PROFILE=~/.Rprofile.site
  - sudo Rscript -e "install.packages(setdiff(c('knitr'), installed.packages())); update.packages(lib.loc = Sys.getenv('R_LIBS_USER'), ask = FALSE, checkBuilt = TRUE)"
  - rvm default
  - gem install json kramdown jekyll bundler

install:
  - pip install pyyaml

script:
  - make lesson-check-all
  - make --always-make site
